name: "Snowflake Terraform Demo Workflow"

on:
  workflow_dispatch:


jobs:
  snowflake-terraform-demo:
    name: "Snowflake Terraform Demo Job"
    runs-on: ubuntu-latest
    env: 
        snow_user: ${{secrets.SNOWFLAKE_USER}}
        snow_pass: ${{secrets.SNOWFLAKE_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # - name: Terraform Format
      #   id: fmt
      #   run: |
      #     ls -la *
      #     terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: |
          ls -la *
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          ls -la *
          terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: |
          ls -la *
          terraform apply -auto-approve